version: '3.8'

services:
  # Backend API
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgresql://postgres:password@postgres:5432/ai_code_platform
      - OPENAI_API_KEY=${OPENAI_API_KEY:-demo}
      - ANTHROPIC_API_KEY=${ANTHROPIC_API_KEY:-demo}
    depends_on:
      - postgres
    volumes:
      - ./backend:/app
    restart: unless-stopped
    networks:
      - ai-code-platform

  # Frontend
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:80"
    environment:
      - REACT_APP_API_URL=http://localhost:8000
    depends_on:
      - backend
    restart: unless-stopped
    networks:
      - ai-code-platform

  # PostgreSQL Database
  postgres:
    image: postgres:15-alpine
    environment:
      - POSTGRES_DB=ai_code_platform
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped
    networks:
      - ai-code-platform

volumes:
  postgres_data:

networks:
  ai-code-platform:
    driver: bridge